package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AsigDirIp generated by hbm2java
 */
public class AsigDirIp  implements java.io.Serializable {


     private AsigDirIpId id;
     private DirIp dirIp;
     private Servidor servidor;
     private Date fechaAsig;

    public AsigDirIp() {
    }

    public AsigDirIp(AsigDirIpId id, DirIp dirIp, Servidor servidor, Date fechaAsig) {
       this.id = id;
       this.dirIp = dirIp;
       this.servidor = servidor;
       this.fechaAsig = fechaAsig;
    }
   
    public AsigDirIpId getId() {
        return this.id;
    }
    
    public void setId(AsigDirIpId id) {
        this.id = id;
    }
    public DirIp getDirIp() {
        return this.dirIp;
    }
    
    public void setDirIp(DirIp dirIp) {
        this.dirIp = dirIp;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public Date getFechaAsig() {
        return this.fechaAsig;
    }
    
    public void setFechaAsig(Date fechaAsig) {
        this.fechaAsig = fechaAsig;
    }




}


