package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1



/**
 * AsigDirIpId generated by hbm2java
 */
public class AsigDirIpId  implements java.io.Serializable {


     private short idDir;
     private short idServ;

    public AsigDirIpId() {
    }

    public AsigDirIpId(short idDir, short idServ) {
       this.idDir = idDir;
       this.idServ = idServ;
    }
   
    public short getIdDir() {
        return this.idDir;
    }
    
    public void setIdDir(short idDir) {
        this.idDir = idDir;
    }
    public short getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(short idServ) {
        this.idServ = idServ;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsigDirIpId) ) return false;
		 AsigDirIpId castOther = ( AsigDirIpId ) other; 
         
		 return (this.getIdDir()==castOther.getIdDir())
 && (this.getIdServ()==castOther.getIdServ());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdDir();
         result = 37 * result + this.getIdServ();
         return result;
   }   


}


