package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CarServ generated by hbm2java
 */
public class CarServ  implements java.io.Serializable {


     private short idCarServ;
     private String soServ;
     private int tamDiscServ;
     private int tamMemServ;
     private Set servidors = new HashSet(0);

    public CarServ() {
    }

	
    public CarServ(short idCarServ, String soServ, int tamDiscServ, int tamMemServ) {
        this.idCarServ = idCarServ;
        this.soServ = soServ;
        this.tamDiscServ = tamDiscServ;
        this.tamMemServ = tamMemServ;
    }
    public CarServ(short idCarServ, String soServ, int tamDiscServ, int tamMemServ, Set servidors) {
       this.idCarServ = idCarServ;
       this.soServ = soServ;
       this.tamDiscServ = tamDiscServ;
       this.tamMemServ = tamMemServ;
       this.servidors = servidors;
    }
   
    public short getIdCarServ() {
        return this.idCarServ;
    }
    
    public void setIdCarServ(short idCarServ) {
        this.idCarServ = idCarServ;
    }
    public String getSoServ() {
        return this.soServ;
    }
    
    public void setSoServ(String soServ) {
        this.soServ = soServ;
    }
    public int getTamDiscServ() {
        return this.tamDiscServ;
    }
    
    public void setTamDiscServ(int tamDiscServ) {
        this.tamDiscServ = tamDiscServ;
    }
    public int getTamMemServ() {
        return this.tamMemServ;
    }
    
    public void setTamMemServ(int tamMemServ) {
        this.tamMemServ = tamMemServ;
    }
    public Set getServidors() {
        return this.servidors;
    }
    
    public void setServidors(Set servidors) {
        this.servidors = servidors;
    }




}


