package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ContGar generated by hbm2java
 */
public class ContGar  implements java.io.Serializable {


     private short idCont;
     private String nomCont;
     private String correoCont;
     private int fonoCont;
     private Set garantias = new HashSet(0);

    public ContGar() {
    }

	
    public ContGar(short idCont, String nomCont, String correoCont, int fonoCont) {
        this.idCont = idCont;
        this.nomCont = nomCont;
        this.correoCont = correoCont;
        this.fonoCont = fonoCont;
    }
    public ContGar(short idCont, String nomCont, String correoCont, int fonoCont, Set garantias) {
       this.idCont = idCont;
       this.nomCont = nomCont;
       this.correoCont = correoCont;
       this.fonoCont = fonoCont;
       this.garantias = garantias;
    }
   
    public short getIdCont() {
        return this.idCont;
    }
    
    public void setIdCont(short idCont) {
        this.idCont = idCont;
    }
    public String getNomCont() {
        return this.nomCont;
    }
    
    public void setNomCont(String nomCont) {
        this.nomCont = nomCont;
    }
    public String getCorreoCont() {
        return this.correoCont;
    }
    
    public void setCorreoCont(String correoCont) {
        this.correoCont = correoCont;
    }
    public int getFonoCont() {
        return this.fonoCont;
    }
    
    public void setFonoCont(int fonoCont) {
        this.fonoCont = fonoCont;
    }
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }




}


