package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DirIp generated by hbm2java
 */
public class DirIp  implements java.io.Serializable {


     private short idDir;
     private String dirIp;
     private Set asigDirIps = new HashSet(0);

    public DirIp() {
    }

	
    public DirIp(short idDir, String dirIp) {
        this.idDir = idDir;
        this.dirIp = dirIp;
    }
    public DirIp(short idDir, String dirIp, Set asigDirIps) {
       this.idDir = idDir;
       this.dirIp = dirIp;
       this.asigDirIps = asigDirIps;
    }
   
    public short getIdDir() {
        return this.idDir;
    }
    
    public void setIdDir(short idDir) {
        this.idDir = idDir;
    }
    public String getDirIp() {
        return this.dirIp;
    }
    
    public void setDirIp(String dirIp) {
        this.dirIp = dirIp;
    }
    public Set getAsigDirIps() {
        return this.asigDirIps;
    }
    
    public void setAsigDirIps(Set asigDirIps) {
        this.asigDirIps = asigDirIps;
    }




}


