package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DirIp generated by hbm2java
 */
public class DirIp  implements java.io.Serializable {


     private short idDir;
     private String dirIp;
     private Set servidors = new HashSet(0);

    public DirIp() {
    }

	
    public DirIp(short idDir, String dirIp) {
        this.idDir = idDir;
        this.dirIp = dirIp;
    }
    public DirIp(short idDir, String dirIp, Set servidors) {
       this.idDir = idDir;
       this.dirIp = dirIp;
       this.servidors = servidors;
    }
   
    public short getIdDir() {
        return this.idDir;
    }
    
    public void setIdDir(short idDir) {
        this.idDir = idDir;
    }
    public String getDirIp() {
        return this.dirIp;
    }
    
    public void setDirIp(String dirIp) {
        this.dirIp = dirIp;
    }
    public Set getServidors() {
        return this.servidors;
    }
    
    public void setServidors(Set servidors) {
        this.servidors = servidors;
    }




}


