package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Garantia generated by hbm2java
 */
public class Garantia  implements java.io.Serializable {


     private short idGar;
     private ContGar contGar;
     private String nomGar;
     private Date fechaGar;
     private Date fechaCadGar;
     private Set servidors = new HashSet(0);

    public Garantia() {
    }

	
    public Garantia(short idGar, String nomGar, Date fechaGar, Date fechaCadGar) {
        this.idGar = idGar;
        this.nomGar = nomGar;
        this.fechaGar = fechaGar;
        this.fechaCadGar = fechaCadGar;
    }
    public Garantia(short idGar, ContGar contGar, String nomGar, Date fechaGar, Date fechaCadGar, Set servidors) {
       this.idGar = idGar;
       this.contGar = contGar;
       this.nomGar = nomGar;
       this.fechaGar = fechaGar;
       this.fechaCadGar = fechaCadGar;
       this.servidors = servidors;
    }
   
    public short getIdGar() {
        return this.idGar;
    }
    
    public void setIdGar(short idGar) {
        this.idGar = idGar;
    }
    public ContGar getContGar() {
        return this.contGar;
    }
    
    public void setContGar(ContGar contGar) {
        this.contGar = contGar;
    }
    public String getNomGar() {
        return this.nomGar;
    }
    
    public void setNomGar(String nomGar) {
        this.nomGar = nomGar;
    }
    public Date getFechaGar() {
        return this.fechaGar;
    }
    
    public void setFechaGar(Date fechaGar) {
        this.fechaGar = fechaGar;
    }
    public Date getFechaCadGar() {
        return this.fechaCadGar;
    }
    
    public void setFechaCadGar(Date fechaCadGar) {
        this.fechaCadGar = fechaCadGar;
    }
    public Set getServidors() {
        return this.servidors;
    }
    
    public void setServidors(Set servidors) {
        this.servidors = servidors;
    }




}


