package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Garantia generated by hbm2java
 */
public class Garantia  implements java.io.Serializable {


     private short idGar;
     private ContGar contGar;
     private Servidor servidor;
     private String nomGar;
     private Date fechaGar;
     private Date fechaCadGar;

    public Garantia() {
    }

	
    public Garantia(short idGar, String nomGar, Date fechaGar, Date fechaCadGar) {
        this.idGar = idGar;
        this.nomGar = nomGar;
        this.fechaGar = fechaGar;
        this.fechaCadGar = fechaCadGar;
    }
    public Garantia(short idGar, ContGar contGar, Servidor servidor, String nomGar, Date fechaGar, Date fechaCadGar) {
       this.idGar = idGar;
       this.contGar = contGar;
       this.servidor = servidor;
       this.nomGar = nomGar;
       this.fechaGar = fechaGar;
       this.fechaCadGar = fechaCadGar;
    }
   
    public short getIdGar() {
        return this.idGar;
    }
    
    public void setIdGar(short idGar) {
        this.idGar = idGar;
    }
    public ContGar getContGar() {
        return this.contGar;
    }
    
    public void setContGar(ContGar contGar) {
        this.contGar = contGar;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public String getNomGar() {
        return this.nomGar;
    }
    
    public void setNomGar(String nomGar) {
        this.nomGar = nomGar;
    }
    public Date getFechaGar() {
        return this.fechaGar;
    }
    
    public void setFechaGar(Date fechaGar) {
        this.fechaGar = fechaGar;
    }
    public Date getFechaCadGar() {
        return this.fechaCadGar;
    }
    
    public void setFechaCadGar(Date fechaCadGar) {
        this.fechaCadGar = fechaCadGar;
    }




}


