package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1



/**
 * Incidente generated by hbm2java
 */
public class Incidente  implements java.io.Serializable {


     private short idIncidente;
     private Servidor servidor;
     private Sistema sistema;
     private UnidadTrabajo unidadTrabajo;
     private String probIncid;
     private String solIncid;
     private Short TInacIncid;
     private char activoIncid;

    public Incidente() {
    }

	
    public Incidente(short idIncidente, String probIncid, char activoIncid) {
        this.idIncidente = idIncidente;
        this.probIncid = probIncid;
        this.activoIncid = activoIncid;
    }
    public Incidente(short idIncidente, Servidor servidor, Sistema sistema, UnidadTrabajo unidadTrabajo, String probIncid, String solIncid, Short TInacIncid, char activoIncid) {
       this.idIncidente = idIncidente;
       this.servidor = servidor;
       this.sistema = sistema;
       this.unidadTrabajo = unidadTrabajo;
       this.probIncid = probIncid;
       this.solIncid = solIncid;
       this.TInacIncid = TInacIncid;
       this.activoIncid = activoIncid;
    }
   
    public short getIdIncidente() {
        return this.idIncidente;
    }
    
    public void setIdIncidente(short idIncidente) {
        this.idIncidente = idIncidente;
    }
    public Servidor getServidor() {
        return this.servidor;
    }
    
    public void setServidor(Servidor servidor) {
        this.servidor = servidor;
    }
    public Sistema getSistema() {
        return this.sistema;
    }
    
    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    public UnidadTrabajo getUnidadTrabajo() {
        return this.unidadTrabajo;
    }
    
    public void setUnidadTrabajo(UnidadTrabajo unidadTrabajo) {
        this.unidadTrabajo = unidadTrabajo;
    }
    public String getProbIncid() {
        return this.probIncid;
    }
    
    public void setProbIncid(String probIncid) {
        this.probIncid = probIncid;
    }
    public String getSolIncid() {
        return this.solIncid;
    }
    
    public void setSolIncid(String solIncid) {
        this.solIncid = solIncid;
    }
    public Short getTInacIncid() {
        return this.TInacIncid;
    }
    
    public void setTInacIncid(Short TInacIncid) {
        this.TInacIncid = TInacIncid;
    }
    public char getActivoIncid() {
        return this.activoIncid;
    }
    
    public void setActivoIncid(char activoIncid) {
        this.activoIncid = activoIncid;
    }




}


