package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1



/**
 * LengDesSist generated by hbm2java
 */
public class LengDesSist  implements java.io.Serializable {


     private short idLengSist;
     private String nomLengDes;

    public LengDesSist() {
    }

    public LengDesSist(short idLengSist, String nomLengDes) {
       this.idLengSist = idLengSist;
       this.nomLengDes = nomLengDes;
    }
   
    public short getIdLengSist() {
        return this.idLengSist;
    }
    
    public void setIdLengSist(short idLengSist) {
        this.idLengSist = idLengSist;
    }
    public String getNomLengDes() {
        return this.nomLengDes;
    }
    
    public void setNomLengDes(String nomLengDes) {
        this.nomLengDes = nomLengDes;
    }




}


