package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * LengDesSist generated by hbm2java
 */
public class LengDesSist  implements java.io.Serializable {


     private short idLengSist;
     private String nomLengDes;
     private Set sistemas = new HashSet(0);

    public LengDesSist() {
    }

	
    public LengDesSist(short idLengSist, String nomLengDes) {
        this.idLengSist = idLengSist;
        this.nomLengDes = nomLengDes;
    }
    public LengDesSist(short idLengSist, String nomLengDes, Set sistemas) {
       this.idLengSist = idLengSist;
       this.nomLengDes = nomLengDes;
       this.sistemas = sistemas;
    }
   
    public short getIdLengSist() {
        return this.idLengSist;
    }
    
    public void setIdLengSist(short idLengSist) {
        this.idLengSist = idLengSist;
    }
    public String getNomLengDes() {
        return this.nomLengDes;
    }
    
    public void setNomLengDes(String nomLengDes) {
        this.nomLengDes = nomLengDes;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }




}


