package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NivSeg generated by hbm2java
 */
public class NivSeg  implements java.io.Serializable {


     private short idNivSeg;
     private String descNivSeg;
     private Set sistemas = new HashSet(0);

    public NivSeg() {
    }

	
    public NivSeg(short idNivSeg, String descNivSeg) {
        this.idNivSeg = idNivSeg;
        this.descNivSeg = descNivSeg;
    }
    public NivSeg(short idNivSeg, String descNivSeg, Set sistemas) {
       this.idNivSeg = idNivSeg;
       this.descNivSeg = descNivSeg;
       this.sistemas = sistemas;
    }
   
    public short getIdNivSeg() {
        return this.idNivSeg;
    }
    
    public void setIdNivSeg(short idNivSeg) {
        this.idNivSeg = idNivSeg;
    }
    public String getDescNivSeg() {
        return this.descNivSeg;
    }
    
    public void setDescNivSeg(String descNivSeg) {
        this.descNivSeg = descNivSeg;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }




}


