package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * NivSeg generated by hbm2java
 */
public class NivSeg  implements java.io.Serializable {


     private int idNivSeg;
     private String descNivSeg;
     private Set sistemas = new HashSet(0);

    public NivSeg() {
    }

	
    public NivSeg(int idNivSeg, String descNivSeg) {
        this.idNivSeg = idNivSeg;
        this.descNivSeg = descNivSeg;
    }
    public NivSeg(int idNivSeg, String descNivSeg, Set sistemas) {
       this.idNivSeg = idNivSeg;
       this.descNivSeg = descNivSeg;
       this.sistemas = sistemas;
    }
   
    public int getIdNivSeg() {
        return this.idNivSeg;
    }
    
    public void setIdNivSeg(int idNivSeg) {
        this.idNivSeg = idNivSeg;
    }
    public String getDescNivSeg() {
        return this.descNivSeg;
    }
    
    public void setDescNivSeg(String descNivSeg) {
        this.descNivSeg = descNivSeg;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }




}


