package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organizacion generated by hbm2java
 */
public class Organizacion  implements java.io.Serializable {


     private short idOrg;
     private String nomOrg;
     private Set sistemas = new HashSet(0);

    public Organizacion() {
    }

	
    public Organizacion(short idOrg, String nomOrg) {
        this.idOrg = idOrg;
        this.nomOrg = nomOrg;
    }
    public Organizacion(short idOrg, String nomOrg, Set sistemas) {
       this.idOrg = idOrg;
       this.nomOrg = nomOrg;
       this.sistemas = sistemas;
    }
   
    public short getIdOrg() {
        return this.idOrg;
    }
    
    public void setIdOrg(short idOrg) {
        this.idOrg = idOrg;
    }
    public String getNomOrg() {
        return this.nomOrg;
    }
    
    public void setNomOrg(String nomOrg) {
        this.nomOrg = nomOrg;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }




}


