package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private short idProv;
     private String nomProv;
     private String correoProv;
     private String fonoProv;
     private Set sistemas = new HashSet(0);
     private Set servidors = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(short idProv, String nomProv, String correoProv, String fonoProv) {
        this.idProv = idProv;
        this.nomProv = nomProv;
        this.correoProv = correoProv;
        this.fonoProv = fonoProv;
    }
    public Proveedor(short idProv, String nomProv, String correoProv, String fonoProv, Set sistemas, Set servidors) {
       this.idProv = idProv;
       this.nomProv = nomProv;
       this.correoProv = correoProv;
       this.fonoProv = fonoProv;
       this.sistemas = sistemas;
       this.servidors = servidors;
    }
   
    public short getIdProv() {
        return this.idProv;
    }
    
    public void setIdProv(short idProv) {
        this.idProv = idProv;
    }
    public String getNomProv() {
        return this.nomProv;
    }
    
    public void setNomProv(String nomProv) {
        this.nomProv = nomProv;
    }
    public String getCorreoProv() {
        return this.correoProv;
    }
    
    public void setCorreoProv(String correoProv) {
        this.correoProv = correoProv;
    }
    public String getFonoProv() {
        return this.fonoProv;
    }
    
    public void setFonoProv(String fonoProv) {
        this.fonoProv = fonoProv;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }
    public Set getServidors() {
        return this.servidors;
    }
    
    public void setServidors(Set servidors) {
        this.servidors = servidors;
    }




}


