package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SalaServ generated by hbm2java
 */
public class SalaServ  implements java.io.Serializable {


     private short idSalaServ;
     private String nomSalaServ;
     private Set racks = new HashSet(0);

    public SalaServ() {
    }

	
    public SalaServ(short idSalaServ, String nomSalaServ) {
        this.idSalaServ = idSalaServ;
        this.nomSalaServ = nomSalaServ;
    }
    public SalaServ(short idSalaServ, String nomSalaServ, Set racks) {
       this.idSalaServ = idSalaServ;
       this.nomSalaServ = nomSalaServ;
       this.racks = racks;
    }
   
    public short getIdSalaServ() {
        return this.idSalaServ;
    }
    
    public void setIdSalaServ(short idSalaServ) {
        this.idSalaServ = idSalaServ;
    }
    public String getNomSalaServ() {
        return this.nomSalaServ;
    }
    
    public void setNomSalaServ(String nomSalaServ) {
        this.nomSalaServ = nomSalaServ;
    }
    public Set getRacks() {
        return this.racks;
    }
    
    public void setRacks(Set racks) {
        this.racks = racks;
    }




}


