package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1



/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private short idServicio;
     private Sistema sistema;
     private String nomServicio;

    public Servicio() {
    }

    public Servicio(short idServicio, Sistema sistema, String nomServicio) {
       this.idServicio = idServicio;
       this.sistema = sistema;
       this.nomServicio = nomServicio;
    }
   
    public short getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(short idServicio) {
        this.idServicio = idServicio;
    }
    public Sistema getSistema() {
        return this.sistema;
    }
    
    public void setSistema(Sistema sistema) {
        this.sistema = sistema;
    }
    public String getNomServicio() {
        return this.nomServicio;
    }
    
    public void setNomServicio(String nomServicio) {
        this.nomServicio = nomServicio;
    }




}


