package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Servidor generated by hbm2java
 */
public class Servidor implements java.io.Serializable {

    private short idServ;
    private CarServ carServ;
    private Rack rack;
    private SalaServ salaServ;
    private SistOper sistOper;
    private TipoServ tipoServ;
    private Usuario usuario;
    private TipoServidor tipoServidor;
    private String nomServ;
    private String marcaServ;
    private String modeloServ;
    private Proveedor proveedor;
    private Set asigDirIps = new HashSet(0);
    private Set garantias = new HashSet(0);
    private Set incidentes = new HashSet(0);
    private Set sistemas = new HashSet(0);

    public Servidor() {
    }

    public Servidor(short idServ, String nomServ, String marcaServ, String modeloServ) {
        this.idServ = idServ;
        this.nomServ = nomServ;
        this.marcaServ = marcaServ;
        this.modeloServ = modeloServ;
    }

    public Servidor(short idServ, CarServ carServ, Rack rack, SalaServ salaServ, SistOper sistOper, TipoServ tipoServ, Usuario usuario, TipoServidor tipoServidor, String nomServ, String marcaServ, String modeloServ, Short idProv, Set asigDirIps, Set garantias, Set incidentes, Set sistemas) {
        this.idServ = idServ;
        this.carServ = carServ;
        this.rack = rack;
        this.salaServ = salaServ;
        this.sistOper = sistOper;
        this.tipoServ = tipoServ;
        this.usuario = usuario;
        this.tipoServidor = tipoServidor;
        this.nomServ = nomServ;
        this.marcaServ = marcaServ;
        this.modeloServ = modeloServ;
        this.proveedor = proveedor;
        this.asigDirIps = asigDirIps;
        this.garantias = garantias;
        this.incidentes = incidentes;
        this.sistemas = sistemas;
    }

    public short getIdServ() {
        return this.idServ;
    }

    public void setIdServ(short idServ) {
        this.idServ = idServ;
    }

    public CarServ getCarServ() {
        return this.carServ;
    }

    public void setCarServ(CarServ carServ) {
        this.carServ = carServ;
    }

    public Rack getRack() {
        return this.rack;
    }

    public void setRack(Rack rack) {
        this.rack = rack;
    }

    public SalaServ getSalaServ() {
        return this.salaServ;
    }

    public void setSalaServ(SalaServ salaServ) {
        this.salaServ = salaServ;
    }

    public SistOper getSistOper() {
        return this.sistOper;
    }

    public void setSistOper(SistOper sistOper) {
        this.sistOper = sistOper;
    }

    public TipoServ getTipoServ() {
        return this.tipoServ;
    }

    public void setTipoServ(TipoServ tipoServ) {
        this.tipoServ = tipoServ;
    }

    public Usuario getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public TipoServidor getTipoServidor() {
        return this.tipoServidor;
    }

    public void setTipoServidor(TipoServidor tipoServidor) {
        this.tipoServidor = tipoServidor;
    }

    public String getNomServ() {
        return this.nomServ;
    }

    public void setNomServ(String nomServ) {
        this.nomServ = nomServ;
    }

    public String getMarcaServ() {
        return this.marcaServ;
    }

    public void setMarcaServ(String marcaServ) {
        this.marcaServ = marcaServ;
    }

    public String getModeloServ() {
        return this.modeloServ;
    }

    public void setModeloServ(String modeloServ) {
        this.modeloServ = modeloServ;
    }

    public Proveedor getProveedor() {
        return proveedor;
    }

    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    public Set getAsigDirIps() {
        return this.asigDirIps;
    }

    public void setAsigDirIps(Set asigDirIps) {
        this.asigDirIps = asigDirIps;
    }

    public Set getGarantias() {
        return this.garantias;
    }

    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }

    public Set getIncidentes() {
        return this.incidentes;
    }

    public void setIncidentes(Set incidentes) {
        this.incidentes = incidentes;
    }

    public Set getSistemas() {
        return this.sistemas;
    }

    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }

}
