package POJO;
// Generated 06-12-2016 23:27:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servidor generated by hbm2java
 */
public class Servidor  implements java.io.Serializable {


     private short idServ;
     private DirIp dirIp;
     private Garantia garantia;
     private Proveedor proveedor;
     private Rack rack;
     private SistOper sistOper;
     private Usuario usuario;
     private String nomServ;
     private String marcaServ;
     private String modeloServ;
     private Integer tamMemoria;
     private Integer tamDisco;
     private String passAdmin;
     private String userBd;
     private String passBd;
     private Set incidentes = new HashSet(0);
     private Set sistemas = new HashSet(0);

    public Servidor() {
    }

	
    public Servidor(short idServ, DirIp dirIp, String nomServ, String marcaServ, String modeloServ, Integer tamMemoria, Integer tamDisco) {
        this.idServ = idServ;
        this.dirIp = dirIp;
        this.nomServ = nomServ;
        this.marcaServ = marcaServ;
        this.modeloServ = modeloServ;
        this.tamMemoria = tamMemoria;
        this.tamDisco = tamDisco;
    }
    public Servidor(short idServ, DirIp dirIp, Garantia garantia, Proveedor proveedor, Rack rack, SistOper sistOper, Usuario usuario, String nomServ, String marcaServ, String modeloServ, Integer tamMemoria, Integer tamDisco, String passAdmin, String userBd, String passBd, Set incidentes, Set sistemas) {
       this.idServ = idServ;
       this.dirIp = dirIp;
       this.garantia = garantia;
       this.proveedor = proveedor;
       this.rack = rack;
       this.sistOper = sistOper;
       this.usuario = usuario;
       this.nomServ = nomServ;
       this.marcaServ = marcaServ;
       this.modeloServ = modeloServ;
       this.tamMemoria = tamMemoria;
       this.tamDisco = tamDisco;
       this.passAdmin = passAdmin;
       this.userBd = userBd;
       this.passBd = passBd;
       this.incidentes = incidentes;
       this.sistemas = sistemas;
    }
   
    public short getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(short idServ) {
        this.idServ = idServ;
    }
    public DirIp getDirIp() {
        return this.dirIp;
    }
    
    public void setDirIp(DirIp dirIp) {
        this.dirIp = dirIp;
    }
    public Garantia getGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(Garantia garantia) {
        this.garantia = garantia;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Rack getRack() {
        return this.rack;
    }
    
    public void setRack(Rack rack) {
        this.rack = rack;
    }
    public SistOper getSistOper() {
        return this.sistOper;
    }
    
    public void setSistOper(SistOper sistOper) {
        this.sistOper = sistOper;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNomServ() {
        return this.nomServ;
    }
    
    public void setNomServ(String nomServ) {
        this.nomServ = nomServ;
    }
    public String getMarcaServ() {
        return this.marcaServ;
    }
    
    public void setMarcaServ(String marcaServ) {
        this.marcaServ = marcaServ;
    }
    public String getModeloServ() {
        return this.modeloServ;
    }
    
    public void setModeloServ(String modeloServ) {
        this.modeloServ = modeloServ;
    }
    public Integer getTamMemoria() {
        return this.tamMemoria;
    }
    
    public void setTamMemoria(Integer tamMemoria) {
        this.tamMemoria = tamMemoria;
    }
    public Integer getTamDisco() {
        return this.tamDisco;
    }
    
    public void setTamDisco(Integer tamDisco) {
        this.tamDisco = tamDisco;
    }
    public String getPassAdmin() {
        return this.passAdmin;
    }
    
    public void setPassAdmin(String passAdmin) {
        this.passAdmin = passAdmin;
    }
    public String getUserBd() {
        return this.userBd;
    }
    
    public void setUserBd(String userBd) {
        this.userBd = userBd;
    }
    public String getPassBd() {
        return this.passBd;
    }
    
    public void setPassBd(String passBd) {
        this.passBd = passBd;
    }
    public Set getIncidentes() {
        return this.incidentes;
    }
    
    public void setIncidentes(Set incidentes) {
        this.incidentes = incidentes;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }




}


