package POJO;
// Generated 03-11-2016 5:17:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Servidor generated by hbm2java
 */
public class Servidor  implements java.io.Serializable {


     private short idServ;
     private CarServ carServ;
     private DirIp dirIp;
     private Garantia garantia;
     private Proveedor proveedor;
     private Rack rack;
     private SistOper sistOper;
     private TipoServ tipoServ;
     private Usuario usuario;
     private String nomServ;
     private String marcaServ;
     private String modeloServ;
     private Set incidentes = new HashSet(0);
     private Set sistemas = new HashSet(0);

    public Servidor() {
    }

	
    public Servidor(short idServ, DirIp dirIp, String nomServ, String marcaServ, String modeloServ) {
        this.idServ = idServ;
        this.dirIp = dirIp;
        this.nomServ = nomServ;
        this.marcaServ = marcaServ;
        this.modeloServ = modeloServ;
    }
    public Servidor(short idServ, CarServ carServ, DirIp dirIp, Garantia garantia, Proveedor proveedor, Rack rack, SistOper sistOper, TipoServ tipoServ, Usuario usuario, String nomServ, String marcaServ, String modeloServ, Set incidentes, Set sistemas) {
       this.idServ = idServ;
       this.carServ = carServ;
       this.dirIp = dirIp;
       this.garantia = garantia;
       this.proveedor = proveedor;
       this.rack = rack;
       this.sistOper = sistOper;
       this.tipoServ = tipoServ;
       this.usuario = usuario;
       this.nomServ = nomServ;
       this.marcaServ = marcaServ;
       this.modeloServ = modeloServ;
       this.incidentes = incidentes;
       this.sistemas = sistemas;
    }
   
    public short getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(short idServ) {
        this.idServ = idServ;
    }
    public CarServ getCarServ() {
        return this.carServ;
    }
    
    public void setCarServ(CarServ carServ) {
        this.carServ = carServ;
    }
    public DirIp getDirIp() {
        return this.dirIp;
    }
    
    public void setDirIp(DirIp dirIp) {
        this.dirIp = dirIp;
    }
    public Garantia getGarantia() {
        return this.garantia;
    }
    
    public void setGarantia(Garantia garantia) {
        this.garantia = garantia;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Rack getRack() {
        return this.rack;
    }
    
    public void setRack(Rack rack) {
        this.rack = rack;
    }
    public SistOper getSistOper() {
        return this.sistOper;
    }
    
    public void setSistOper(SistOper sistOper) {
        this.sistOper = sistOper;
    }
    public TipoServ getTipoServ() {
        return this.tipoServ;
    }
    
    public void setTipoServ(TipoServ tipoServ) {
        this.tipoServ = tipoServ;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNomServ() {
        return this.nomServ;
    }
    
    public void setNomServ(String nomServ) {
        this.nomServ = nomServ;
    }
    public String getMarcaServ() {
        return this.marcaServ;
    }
    
    public void setMarcaServ(String marcaServ) {
        this.marcaServ = marcaServ;
    }
    public String getModeloServ() {
        return this.modeloServ;
    }
    
    public void setModeloServ(String modeloServ) {
        this.modeloServ = modeloServ;
    }
    public Set getIncidentes() {
        return this.incidentes;
    }
    
    public void setIncidentes(Set incidentes) {
        this.incidentes = incidentes;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }

    public void setSalaServ(SalaServ byId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


