package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SoftBd generated by hbm2java
 */
public class SoftBd  implements java.io.Serializable {


     private short idSoftBd;
     private String nomSoftBd;
     private String empSoftBd;
     private String verSoftBd;
     private Set sistemas = new HashSet(0);

    public SoftBd() {
    }

	
    public SoftBd(short idSoftBd, String nomSoftBd, String empSoftBd, String verSoftBd) {
        this.idSoftBd = idSoftBd;
        this.nomSoftBd = nomSoftBd;
        this.empSoftBd = empSoftBd;
        this.verSoftBd = verSoftBd;
    }
    public SoftBd(short idSoftBd, String nomSoftBd, String empSoftBd, String verSoftBd, Set sistemas) {
       this.idSoftBd = idSoftBd;
       this.nomSoftBd = nomSoftBd;
       this.empSoftBd = empSoftBd;
       this.verSoftBd = verSoftBd;
       this.sistemas = sistemas;
    }
   
    public short getIdSoftBd() {
        return this.idSoftBd;
    }
    
    public void setIdSoftBd(short idSoftBd) {
        this.idSoftBd = idSoftBd;
    }
    public String getNomSoftBd() {
        return this.nomSoftBd;
    }
    
    public void setNomSoftBd(String nomSoftBd) {
        this.nomSoftBd = nomSoftBd;
    }
    public String getEmpSoftBd() {
        return this.empSoftBd;
    }
    
    public void setEmpSoftBd(String empSoftBd) {
        this.empSoftBd = empSoftBd;
    }
    public String getVerSoftBd() {
        return this.verSoftBd;
    }
    
    public void setVerSoftBd(String verSoftBd) {
        this.verSoftBd = verSoftBd;
    }
    public Set getSistemas() {
        return this.sistemas;
    }
    
    public void setSistemas(Set sistemas) {
        this.sistemas = sistemas;
    }




}


