package POJO;
// Generated 20-10-2016 1:49:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoServidor generated by hbm2java
 */
public class TipoServidor  implements java.io.Serializable {


     private short idTipoServ;
     private String nomTipoServ;
     private Set servidors = new HashSet(0);

    public TipoServidor() {
    }

	
    public TipoServidor(short idTipoServ, String nomTipoServ) {
        this.idTipoServ = idTipoServ;
        this.nomTipoServ = nomTipoServ;
    }
    public TipoServidor(short idTipoServ, String nomTipoServ, Set servidors) {
       this.idTipoServ = idTipoServ;
       this.nomTipoServ = nomTipoServ;
       this.servidors = servidors;
    }
   
    public short getIdTipoServ() {
        return this.idTipoServ;
    }
    
    public void setIdTipoServ(short idTipoServ) {
        this.idTipoServ = idTipoServ;
    }
    public String getNomTipoServ() {
        return this.nomTipoServ;
    }
    
    public void setNomTipoServ(String nomTipoServ) {
        this.nomTipoServ = nomTipoServ;
    }
    public Set getServidors() {
        return this.servidors;
    }
    
    public void setServidors(Set servidors) {
        this.servidors = servidors;
    }




}


