package POJO;
// Generated 06-12-2016 23:27:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadTrabajo generated by hbm2java
 */
public class UnidadTrabajo  implements java.io.Serializable {


     private short idUniTrab;
     private String nomUniTrab;
     private Set incidentes = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public UnidadTrabajo() {
    }

	
    public UnidadTrabajo(short idUniTrab, String nomUniTrab) {
        this.idUniTrab = idUniTrab;
        this.nomUniTrab = nomUniTrab;
    }
    public UnidadTrabajo(short idUniTrab, String nomUniTrab, Set incidentes, Set usuarios) {
       this.idUniTrab = idUniTrab;
       this.nomUniTrab = nomUniTrab;
       this.incidentes = incidentes;
       this.usuarios = usuarios;
    }
   
    public short getIdUniTrab() {
        return this.idUniTrab;
    }
    
    public void setIdUniTrab(short idUniTrab) {
        this.idUniTrab = idUniTrab;
    }
    public String getNomUniTrab() {
        return this.nomUniTrab;
    }
    
    public void setNomUniTrab(String nomUniTrab) {
        this.nomUniTrab = nomUniTrab;
    }
    public Set getIncidentes() {
        return this.incidentes;
    }
    
    public void setIncidentes(Set incidentes) {
        this.incidentes = incidentes;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


